### ISSUE TITLE
 FixtureController private function modified to protected function.

### ISSUE THREAD

**Issue by kids-return** [yiisoft/yii2-faker#22]
FixtureController private function modified to protected function.
Subclasses can override these methods for enhancements.
Can add directly through the template file into the database, without the need to generate data files

**Comment by kids-return** [comment]
I'm sorry I have a poor English

**Comment by dynasource** [comment]
we have to get a better understanding of your usecase to make function protected, and which function are you talking about?

**Comment by kids-return** [comment]
I need to add a save method to the subclass to call parent :: findTemplatesFiles
The save method is mainly through the model directly into the database without generating data files

**Comment by cebe** [comment]
imo it's okay to change it. @kids-return would you like to send a pull request?
