### ISSUE TITLE
email address not comply with RFC 2822

### ISSUE THREAD

**Issue by ventoh** [yiisoft/yii2-faker#23]
I'm triying to do some email simulations. I got an error when i have used some email addresses generate via faker, like this:

Address in mailbox given [nathanaël.riviere@example.com] does not comply with RFC 2822, 3.6.2.
Address in mailbox given [célian.schmitt@example.com] does not comply with RFC 2822, 3.6.2.

**Comment by dynasource** [comment]
out of Yii scope, https://www.google.nl/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi_su66wp7QAhUJOhoKHeYZA2cQFggdMAA&url=https%3A%2F%2Fgithub.com%2Fswiftmailer%2Fswiftmailer%2Fissues%2F382&usg=AFQjCNHmer62hFAoVZp7RPAeT1N8ABHvVw&sig2=Tc5WmV6rVDZIPyt4KfejgA
