### ISSUE TITLE
Unknown formatter "internet"

### ISSUE THREAD

**Issue by adiramardiani** [yiisoft/yii2-faker#7]
I want to add faker for random domain name like `domain.com` and use :
```php
$faker->internet
```
Is throw *Unknown formatter "internet"*

And added
```php
$faker = \Faker\Factory::create();
$faker->addProvider(new \Faker\Provider\Internet($faker));
```
Still same

**Comment by cebe** [comment]
the `Internet` provider does not provide a method named "internet": https://github.com/fzaninotto/Faker#fakerproviderinternet
